<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var array $options
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$assetUrl = $this->plugin('assetUrl');
$hyperlink = $this->plugin('hyperlink');

$baseUrl = $this->serverUrl() . $assetUrl('vendor/verovio/js/', 'Verovio', false, false);
$source = isset($options['source']) ? $options['source'] : $resource->originalUrl();

$this->headLink()
    // Latest compiled and minified CSS.
    ->appendStylesheet($assetUrl('vendor/bootstrap/css/bootstrap.min.css', 'Verovio'))
    // Syntax highlighting CSS.
    ->appendStylesheet($assetUrl('vendor/verovio/css/syntax.css', 'Verovio'))
    // Custom CSS.
    ->appendStylesheet($assetUrl('vendor/verovio/css/verovio.css', 'Verovio'))
    ->appendStylesheet($assetUrl('vendor/verovio/css/verovio-sidebar.css', 'Verovio'))
    ->appendStylesheet($assetUrl('vendor/verovio/css/midiplayer.css', 'Verovio'))
    // Custom CSS for Omeka.
    ->appendStylesheet($assetUrl('css/verovio.css', 'Verovio'))
;

$this->headScript()
    ->prependFile($assetUrl('vendor/jquery/jquery.min.js', 'Omeka'))
    ->appendFile($assetUrl('vendor/jquery/jquery.touchSwipe.min.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/bootstrap/js/bootstrap.bundle.min.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/bootstrap-contextmenu/bootstrap-contextmenu.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/filesaver/FileSaver.min.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/d3/d3.min.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/jquery/jquery.cookie.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/jsonform/jsonform.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    // Verovio.
    // Use this to increase the memory for Verovio.
    // ->appendFile($assetUrl('vendor/verovio/js/verovio-memory.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/verovio/js/verovio-toolkit.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    // Midi-player for playback in the editor.
    ->appendFile($assetUrl('vendor/verovio/js/midi-player/wildwebmidi.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/verovio/js/midi-player/midiplayer.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    // Pdf kit.
    ->appendFile($assetUrl('vendor/verovio/js/pdfkit/blobstream.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/verovio/js/pdfkit/pdfkit.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/verovio/js/pdfkit/source.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('vendor/verovio/js/pdfkit/vrv-ttf.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
    // Init and custom for Omeka.
    ->appendFile($assetUrl('js/verovio-mei-viewer.js', 'Verovio'), 'text/javascript', ['defer' => 'defer'])
;
?>

<?php if (!empty($options['heading'])): ?>
    <h2><?= $options['heading'] ?></h2>
<?php endif; ?>

<div id="verovio" class="verovio" data-base-url="<?= $escape($baseUrl) ?>" data-url="<?= $escape($source) ?>">
    <?= $translate('The viewer is loading…') ?>
</div>

<div id="verovio-offcanvas" class="verovio row-offcanvas row-offcanvas-right" <?= $options['attributes'] ?>>

<!-- modal -->
<div class="modal fade" id="errorDialog" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="<?= $translate('Close') ?>"><span aria-hidden="true" class="glyphicon glyphicon-remove"> </span></button>
                <h4 class="modal-title" id="myModalLabel"><?= $translate('Error') ?></h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger" role="alert">
                    <?= $translate('Sorry, Verovio failed to process the MEI data.') ?>
                </div>
                <div id="errDiv">
                    <pre id="err"></pre>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- sidebar -->
<div class="sidebar-offcanvas sidebar-right" id="sidebar" role="navigation">
    <div class="sidebar-panel">
        <div class="row">
            <div class="col-12">
                 <h4><?= $translate('Navigation') ?></h4>
            </div>
        </div>
        <div class="row sidebar-row">
            <div class="col-12">
                <button class="btn btn-secondary btn-sm float-left popover-btn" type="button" data-container="body" data-toggle="popover" data-placement="left" data-content="<?= $escape($translate('On mobile devices, you can swipe left or right to change page and tap or double tap to zoom-in or zoom-out. On desktops, you can use [ctrl+] left or right arrows and +/- keys.')) ?>">
                    <span class="glyphicon glyphicon-question-sign"/>
                </button>
            </div>
        </div>
        <div class="row sidebar-row">
            <div class="col-lg-12">
                <p>
                    <?= sprintf($translate('Go to page [1-%s]:'), '<span id="total_text">1</span>') ?>
                </p>
                <div class="input-group input-group-sm" style="width: 20px;">
                    <span class="input-group-btn">
                        <button id="first-page-button" class="btn btn-secondary" type="button">
                            <span class="glyphicon glyphicon-fast-backward"/>
                        </button>
                        <button id="prev-page-button" class="btn btn-secondary" type="button">
                            <span class="glyphicon glyphicon-backward"/>
                        </button>
                    </span>
                    <input id="jump-text" type="text" class="form-control" placeholder="0" style="width: 45px !important;"/>
                    <span class="input-group-btn">
                        <button id="next-page-button" class="btn btn-secondary" type="button">
                            <span class="glyphicon glyphicon-forward"/>
                        </button>
                        <button id="last-page-button" class="btn btn-secondary" type="button">
                            <span class="glyphicon glyphicon-fast-forward"/>
                        </button>
                    </span>
                </div>
                <p></p>
                <p><em><?= $translate('(Swipe or click left- or right-key to change screen)') ?></em></p>
                <!-- /input-group -->
            </div>
            <!-- /.col-xl-6 -->
        </div>
        <div class="row sidebar-row">
            <div class="col-lg-6">
                <p>
                    <?= $translate('Zoom:') ?>
                </p>
                <div class="input-group input-group-sm" style="width: 20px;">
                    <span class="input-group-btn">
                        <button id="zoom-out-button" class="btn btn-secondary" type="button">
                            <span class="glyphicon glyphicon-zoom-out">
                        </span></button>
                    </span>
                    <input id="zoom-text" type="text" class="form-control" style="width:60px !important;" placeholder="100%"/>
                    <span class="input-group-btn">
                        <button id="zoom-in-button" class="btn btn-secondary" type="button">
                            <span class="glyphicon glyphicon-zoom-in"/>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </div>
            <!-- /.col-lg-6 -->
        </div>
    </div>

    <div class="sidebar-panel">
        <div class="row">
            <div class="col-12">
                <h4><?= $translate('Examples') ?></h4>
            </div>
        </div>
        <div id="downloads_panel_body">
            <div class="row">
                <div class="col-lg-12">
                    <?php $examples = [
                        ['file' => 'Brahms_StringQuartet_Op51_No1.mei', 'title' => 'Brahms Op 51/1', 'description' => 'String quartet, 7 pages - 640Kb'],
                        ['file' => 'Chopin_Etude_op.10_no.9.mei', 'title' => 'Chopin op.10/9', 'description' => 'Etude, 3 pages - 400Kb'],
                        ['file' => 'Marenzio_Sesto_a_5_01.mei', 'title' => 'Marenzio Madrigal a 5', 'description' => 'Lib. 6, S’io parto, 4 pages - 119Kb'],
                        ['file' => 'Hummel_Concerto_for_trumpet.mei', 'title' => 'Hummel Concerto', 'description' => 'Orchestra score, 121 pages - 7Mb'],
                        ['file' => 'Schubert_Lindenbaum.mei', 'title' => 'Schubert Lied', 'description' => 'Der Lindenbaum, 2 pages - 130Kb'],
                        ['file' => 'Krebs_Trio_Eb_2.mei', 'title' => 'Krebs Trio in Eb', 'description' => 'Organ score, 6 pages - 380Kb'],
                        ['file' => 'Ahle_Jesu_meines_Herzens_Freud.mei', 'title' => 'Ahle, Jesu, meines Herzens Freud', 'description' => 'Choral, 1 page - 70Kb'],
                    ]; ?>
                    <?php foreach ($examples as $example): ?>
                     <div>
                        <p>
                            <?= $hyperlink($example['title'], $assetUrl('vendor/verovio/examples/' . $example['file'])) ?><br/>
                            <?= $example['description'] ?>
                        </p>
                    </div>
                    <?php endforeach; ?>
                </div>
                <!-- /.col-lg-6 -->
            </div>
            <!-- /.row -->
        </div>
    </div>

    <div class="sidebar-panel d-none d-md-block">
        <div class="row">
            <div class="col-12">
                <h4><?= $translate('Select MEI file') ?></h4>
            </div>
        </div>

        <div id="options_panel_body">
            <form id="upload-form" class="form-inline" role="form">
                <div class="row">
                    <div class="col-lg-12">
                        <input id="mei-files" type="file" name="file" style="margin: 4px 0px 8px 0px;"/>
                    </div>
                    <div class="col-lg-12">
                        <button type="submit" id="submit-btn" class="btn btn-secondary btn-sm popover-btn" data-container="body" data-toggle="popover" data-placement="left" data-content="<?= $escape($translate('Click to display the MEI file!')) ?>" data-trigger="manual"><?= $translate('Render') ?></button>
                    </div>
                </div>

                <!--
                <div id="log_panel" style="display: none">
                    <hr class="card"/>
                    <p id="log_p"></p>
                </div>
                -->

            </form>
        </div>
    </div>

    <div class="sidebar-panel">
        <p><?= sprintf($translate('This viewer uses the latest development version %s and might be unstable.'), '<a href="" id="version">[version]</a>') ?></p>
        <p><?= sprintf($translate('Do you need the old MEI viewer? It is available %shere%s.'), '<a href="https://www.verovio.org/mei-viewer-old.xhtml">', '</a>') ?></p>
    </div>

</div>

<div id="page-content-wrapper">
    <!-- top navbar -->
    <div id="navbar" class="navbar navbar-light bg-light navbar-with-sidebar navbar-expand-md">
        <button type="button" class="navbar-toggler sidebar-toggle" data-toggle="offcanvas" data-target=".sidebar-nav">&#x2630;</button>

        <div class="btn-group">
            <button id="pdf-button" class="btn btn-sm btn-secondary" data-toggle="modal" data-target="#pdfDialog" type="button" data-loading-text="<?= $escape($translate('Generating PDF…')) ?>" style="display: none;">
                <span class="hidden-xsd-none d-sm-block"><?= $translate('PDF') ?></span> <span class="glyphicon glyphicon-book"/>
            </button>
            <button id="options-button" class="btn btn-sm btn-secondary hidden-xsd-none d-sm-block" data-toggle="modal" data-target="#optionDialog" type="button" data-loading-text="<?= $escape($translate('Style editor…')) ?>" style="display: none;">
                <span class="hidden-xsd-none d-sm-block"><?= $translate('Options') ?></span> <span class="glyphicon glyphicon-wrench"/>
            </button>
            <button id="play-button" class="btn btn-sm btn-secondary" type="button" style="display: none;" title="<?= $translate('Midi player') ?>">
                <span class="glyphicon glyphicon-volume-up"/>
            </button>
        </div>

        <button type="button" id="mei_download" class="navbar-toggler menu-download" style="display: none;">
            <span class="glyphicon glyphicon-download"></span><span> <?= $translate('MEI') ?></span>
        </button>

        <div class="btn-group">
            <button id="fullscreen-button" class="btn btn-secondary" type="button" title="<?= $escape($translate('Full screen view')) ?>">
                <span class="glyphicon glyphicon-fullscreen"/>
            </button>
        </div>

        <a class="navbar-brand logo-nav" href="https://www.verovio.org">
            <img src="<?= $assetUrl('vendor/verovio/img/verovio-fadded-50.png', 'Verovio') ?>"/>
        </a>
        <div style="clear: both;"></div>
        <hr/>
    </div>

    <div id="svg_panel" style="background-color: #fff;">
        <div id="player" style="z-index: 20; position: absolute; display: none;"></div>
        <div id="svg_output" style="overflow:hidden;" />
    </div>
</div>

<div class="modal fade" id="pdfDialog" role="dialog" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4><?= $translate('PDF options') ?></h4>
            </div>
            <div class="modal-body">
                <form role="form">
                    <div class="form-group">
                        <label for="inputEmail3"><?= $translate('Format') ?></label>
                        <div>
                            <select class="form-control" id="pdfFormat">
                                <option value="A4">A4</option>
                                <option value="letter">Letter</option>
                                <option value="B4">B4</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3"><?= $translate('Orientation') ?></label>
                        <div>
                            <select class="form-control" id="pdfOrientation">
                                <option value="portrait"><?= $translate('Portrait') ?></option>
                                <option value="landscape"><?= $translate('Landscape') ?></option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div class="alert alert-warning" style="text-align:left;">
                    <strong><?= $translate('Warning!') ?></strong> <?= $translate('This is an experimental feature and it can take some time.') ?>
                </div>
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= $translate('Cancel') ?></button>
                <button type="button" id="pdfOK" class="btn btn-primary"><?= $translate('OK') ?></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="optionDialog" role="dialog" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="<?= $escape($translate('Close')) ?>"><span aria-hidden="true">×</span></button>
                <h4><?= $translate('Options') ?></h4>
            </div>
            <div class="modal-body" id="optionDialogContent">
                <div id="option-div">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="optionDefault" class="btn btn-secondary"><?= $translate('Reset to default') ?></button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal"><?= $translate('Cancel') ?></button>
                <button type="button" id="optionOK" class="btn btn-primary"><?= $translate('OK') ?></button>
            </div>
        </div>
    </div>
</div>

</div>

<noscript>
    <p>
        <?= $translate('This browser does not support javascript.') ?>
        <?= sprintf($translate('You may %sdownload it%s to view it offline.'), '<a href="' . $escape($source) . '">', '</a>') ?>
    </p>
</noscript>
