<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var string $source
 * @var string $heading
 * @var string $version
 * @var string $variant Not used with this template
 * @var array $attributes
 *
 * And passed options.
 *
 * Deprecated
 * @var array $options
 */

// Official Verovio simple application viewer.

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$baseUrl = $this->serverUrl() . $assetUrl('vendor/verovio/js/', 'Verovio', false, false);
$source = empty($options['source']) ? $resource->originalUrl() : $options['source'];

$this->headLink()
    ->appendStylesheet($assetUrl('css/verovio.css', 'Verovio'))
;
$this->headScript()
    ->appendFile($assetUrl(empty($version) || $version === 'local' ? 'js/verovio.js' : 'js/verovio-online.js', 'Verovio'), 'module')
;
?>

<?php if (!empty($options['heading'])): ?>
    <h2><?= $options['heading'] ?></h2>
<?php endif; ?>

<div id="verovio" class="verovio" data-base-url="<?= $escape($baseUrl) ?>" data-url="<?= $escape($source) ?>" <?= $options['attributes'] ?>>
    <?= $translate('The viewer is loading…') ?>
</div>
<noscript>
    <p>
        <?= $translate('This browser does not support javascript.') ?>
        <?= sprintf($translate('You may %sdownload it%s to view it offline.'), '<a href="' . $escape($source) . '">', '</a>') ?>
    </p>
</noscript>
