<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\MediaRepresentation $media
 * @var array $options
 */

$translate = $this->plugin('translate');
$assetUrl = $this->plugin('assetUrl');

$baseUrl = $this->serverUrl() . $assetUrl('vendor/verovio/js/', 'Verovio', false, false);

$this->headLink()
    // Latest compiled and minified CSS.
    ->appendStylesheet($assetUrl('vendor/bootstrap/css/bootstrap.min.css', 'Verovio'))
    // Optional theme.
    ->appendStylesheet($assetUrl('vendor/bootstrap/css/bootstrap-theme.min.css', 'Verovio'))
    // Syntax highlighting CSS.
    ->appendStylesheet($assetUrl('vendor/verovio/css/syntax.css', 'Verovio'))
    // Custom CSS.
    ->appendStylesheet($assetUrl('vendor/verovio/css/verovio.css', 'Verovio'))
    ->appendStylesheet($assetUrl('vendor/verovio/css/verovio-sidebar.css', 'Verovio'))
    ->appendStylesheet($assetUrl('vendor/verovio/css/midiplayer.css', 'Verovio'))
    // Custom CSS for Omeka.
    ->appendStylesheet($assetUrl('css/verovio.css', 'Verovio'))
;

$this->headScript()
    // jQuery (necessary for Bootstrap's JavaScript plugins): Verovio uses jQuery > 1.9 and < 3.0.
    // ->prependFile($assetUrl('vendor/jquery/jquery.min.js', 'Omeka'))
    ->appendFile($assetUrl('vendor/jquery/jquery.min.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/jquery/jquery.touchSwipe.min.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/bootstrap/js/bootstrap.min.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/bootstrap-contextmenu/bootstrap-contextmenu.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/filesaver/FileSaver.min.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/d3/d3.min.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/jquery/jquery.cookie.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/jsonform/jsonform.js', 'Verovio'))
    // Verovio.
    // Use this to increase the memory for Verovio.
    // ->appendFile($assetUrl('vendor/verovio/js/verovio-memory.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/verovio/js/verovio-toolkit.js', 'Verovio'))
    // Midi-player for playback in the editor.
    ->appendFile($assetUrl('vendor/verovio/js/midi-player/wildwebmidi.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/verovio/js/midi-player/midiplayer.js', 'Verovio'))
    // Pdf kit.
    ->appendFile($assetUrl('vendor/verovio/js/pdfkit/blobstream.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/verovio/js/pdfkit/pdfkit.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/verovio/js/pdfkit/source.js', 'Verovio'))
    ->appendFile($assetUrl('vendor/verovio/js/pdfkit/vrv-ttf.js', 'Verovio'))
    // Init and custom for Omeka.
    ->appendFile($assetUrl('js/verovio-mei-viewer.js', 'Verovio'))
;
?>

<div id="verovio" class="verovio" data-base-url="<?= $baseUrl ?>" data-url="<?= $media->originalUrl() ?>">
    <?= $translate('The viewer is loading…') ?>
</div>

<div class="verovio row-offcanvas row-offcanvas-right" <?= $options['attributes'] ?>>

<!-- modal -->
<div class="modal fade" id="errorDialog" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" class="glyphicon glyphicon-remove"> </span></button>
                <h4 class="modal-title" id="myModalLabel">Error</h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger" role="alert">Sorry, Verovio failed to process the MEI data</div>
                <div id="errDiv">
                    <pre id="err"></pre>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- sidebar -->
<div class="sidebar-offcanvas sidebar-right" id="sidebar" role="navigation">
    <div class="sidebar-panel">
        <div class="row">
            <div class="col-xs-12">
                <h4>Navigation</h4>
            </div>
        </div>
        <div class="row sidebar-row">
            <div class="col-xs-12">
                <button class="btn btn-default btn-sm pull-left popover-btn" type="button" data-container="body" data-toggle="popover" data-placement="left" data-content="On mobile devices, you can swipe left or right to change page and tap or double tap to zoom-in or zoom-out. On desktops, you can use [ctrl+] left or right arrows and +/- keys.">
                    <span class="glyphicon glyphicon-question-sign"/>
                </button>
            </div>
        </div>
        <div class="row sidebar-row">
            <div class="col-md-12">
                <p>
                    Go to page [1-<span id="total_text">1</span>]:
                </p>
                <div class="input-group input-group-sm" style="width: 20px;">
                    <span class="input-group-btn">
                        <button onclick="first_page()" class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-fast-backward"/>
                        </button>
                        <button onclick="prev_page()" class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-backward"/>
                        </button>
                    </span>
                    <input type="text" class="form-control" placeholder="0" id="jump_text" style="width: 45px !important;" onkeypress="do_page_enter(event)"/>
                    <span class="input-group-btn">
                        <button onclick="next_page()" class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-forward"/>
                        </button>
                        <button onclick="last_page()" class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-fast-forward"/>
                        </button>
                    </span>
                </div>
                <p></p>
                <p><em>(Swipe or click left- or right-key to change screen)</em></p>
                <!-- /input-group -->
            </div>
            <!-- /.col-lg-6 -->
        </div>
        <div class="row sidebar-row">
            <div class="col-md-6">
                <p>
                    Zoom:
                </p>
                <div class="input-group input-group-sm" style="width: 20px;">
                    <span class="input-group-btn">
                        <button onclick="zoom_out()" class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-zoom-out"/>
                        </button>
                    </span>
                    <input type="text" class="form-control" style="width:60px !important;" placeholder="100%" id="zoom_text" onkeypress="do_zoom_enter(event)"/>
                    <span class="input-group-btn">
                        <button onclick="zoom_in()" class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-zoom-in"/>
                        </button>
                    </span>
                </div>
                <!-- /input-group -->
            </div>
            <!-- /.col-md-6 -->
        </div>
    </div>

    <div class="sidebar-panel">
        <div class="row">
            <div class="col-xs-12">
                <h4>Examples</h4>
            </div>
        </div>
        <div id="downloads_panel_body">
            <div class="row">
                <div class="col-md-12">

                    <div >
                        <p>
                        <a href="https://www.verovio.org/mei-viewer.xhtml?file=examples/downloads/Brahms_StringQuartet_Op51_No1.mei">Brahms Op 51/1</a><br/>
                         String quartet, 7 pages - 640Kb
                        </p>
                    </div>

                    <div >
                        <p>
                        <a href="https://www.verovio.org/mei-viewer.xhtml?file=examples/downloads/Chopin_Etude_op.10_no.9.mei">Chopin op.10/9</a><br/>
                         Etude, 3 pages - 400Kb
                        </p>
                    </div>

                    <div >
                        <p>
                        <a href="https://www.verovio.org/mei-viewer.xhtml?file=examples/downloads/Marenzio_Sesto_a_5_01.mei">Marenzio Madrigal a 5</a><br/>
                         Lib. 6, S’io parto, 4 pages - 119Kb
                        </p>
                    </div>

                    <div class="hidden-sm hidden-xs">
                        <p>
                        <a href="https://www.verovio.org/mei-viewer.xhtml?file=examples/downloads/Hummel_Concerto_for_trumpet.mei">Hummel Concerto</a><br/>
                         Orchestra score, 121 pages - 7Mb
                        </p>
                    </div>

                    <div >
                        <p>
                        <a href="https://www.verovio.org/mei-viewer.xhtml?file=examples/downloads/Schubert_Lindenbaum.mei">Schubert Lied</a><br/>
                         Der Lindenbaum, 2 pages - 130Kb
                        </p>
                    </div>

                    <div >
                        <p>
                        <a href="https://www.verovio.org/mei-viewer.xhtml?file=examples/downloads/Krebs_Trio_Eb_2.mei">Krebs Trio in Eb</a><br/>
                         Organ score, 6 pages - 380Kb
                        </p>
                    </div>

                    <div >
                        <p>
                        <a href="https://www.verovio.org/mei-viewer.xhtml?file=examples/downloads/Ahle_Jesu_meines_Herzens_Freud.mei">Ahle, Jesu, meines Herzens Freud</a><br/>
                         Choral, 1 page - 70Kb
                        </p>
                    </div>

                </div>
                <!-- /.col-md-6 -->
            </div>
            <!-- /.row -->
        </div>
    </div>

    <div class="hidden-xs hidden-sm sidebar-panel">
        <div class="row">
            <div class="col-xs-12">
                <h4>Select MEI file</h4>
            </div>
        </div>

        <div id="options_panel_body">
            <form id="upload_form" onsubmit="upload_file( $('#upload_form') ); return false" class="form-inline" role="form">
                <div class="row">
                    <div class="col-md-12">
                        <input type="file" id="mei_files" onchange="$('#submit-btn').popover('show');" name="file" style="margin: 4px 0px 8px 0px;"/>
                    </div>
                    <div class="col-md-12">
                        <button type="submit" id="submit-btn" class="btn btn-default btn-sm popover-btn" data-container="body" data-toggle="popover" data-placement="left" data-content="Click to display the MEI file!" data-trigger="manual">Render</button>
                    </div>
                </div>

                <!--
                <div id="log_panel" style="display: none">
                    <hr class="panel"/>
                    <p id="log_p"></p>
                </div>
                -->

            </form>
        </div>
    </div>

    <div class="sidebar-panel">
        <p>This viewer uses the latest development version <a href="" id="version">[version]</a> and might be unstable.</p>
        <p>Do you need the old MEI viewer? It is available <a href="https://www.verovio.org/mei-viewer-old.xhtml">here</a>.</p>
    </div>

</div>

<div id="page-content-wrapper">
    <!-- top navbar -->
    <div id="navbar" class="navbar navbar-default navbar-with-sidebar">
        <button type="button" class="navbar-toggle sidebar-toggle" data-toggle="offcanvas" data-target=".sidebar-nav">
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
        </button>
        <div class="btn-group">
            <button id="pdf-button" class="btn btn-sm btn-default" data-toggle="modal" data-target="#pdfDialog" type="button" data-loading-text="Generating PDF..." style="display: none;">
                <span class="hidden-xs">PDF </span><span class="glyphicon glyphicon-book"/>
            </button>
            <button id="options-button" class="btn btn-sm btn-default hidden-xs" data-toggle="modal" data-target="#optionDialog" type="button" data-loading-text="Style editor..." style="display: none;">
                <span class="hidden-xs">Options </span><span class="glyphicon glyphicon-wrench"/>
            </button>
            <button id="play-button" onclick="play_midi();" class="btn btn-sm btn-default" type="button" style="display: none;">
                <span class="glyphicon glyphicon-volume-up"/>
            </button>
        </div>

        <button type="button" id="mei_download" class="navbar-toggle menu-download" style="display: none;">
            <span class="glyphicon glyphicon-download"></span><span> MEI</span>
        </button>
        <a class="navbar-brand logo-nav" href="https://www.verovio.org">
            <img src="<?= $assetUrl('vendor/verovio/img/verovio-fadded-50.png', 'Verovio') ?>" />
        </a>
        <div style="clear: both;"></div>
        <hr/>
    </div>

    <div id="svg_panel" style="background-color: #fff;">
        <div id="player" style="z-index: 20; position: absolute; display: none;"></div>
        <div id="svg_output" style="overflow:hidden;" />
    </div>
</div>

<div class="modal fade" id="pdfDialog" role="dialog" style="display: none;">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4>PDF options</h4>
            </div>
            <div class="modal-body">
                <form role="form">
                    <div class="form-group">
                        <label for="inputEmail3">Format</label>
                        <div>
                            <select class="form-control" id="pdfFormat">
                                <option value="A4">A4</option>
                                <option value="letter">Letter</option>
                                <option value="B4">B4</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3">Orientation</label>
                        <div>
                            <select class="form-control" id="pdfOrientation">
                                <option value="portrait">Portrait</option>
                                <option value="landscape">Landscape</option>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <div class="alert alert-warning" style="text-align:left;">
                    <strong>Warning!</strong> This is an experimental feature and it can take some time.
                </div>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" id="pdfOK" class="btn btn-primary">OK</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="optionDialog" role="dialog" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4>Options</h4>
            </div>
            <div class="modal-body" id="optionDialogContent">
                <div id="option-div">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" id="optionDefault" class="btn btn-default">Reset to default</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <button type="button" id="optionOK" class="btn btn-primary">OK</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
//<![CDATA[
    $( document ).ready(function() {

        var version = vrvToolkit.getVersion();
        var n = version.lastIndexOf('-');
        var commit = version.substring(n + 1);
        $('#version').text( version );
        $("#version").attr( "href", "http://github.com/rism-ch/verovio/commit/" + commit ) ;

        $(window).keyup(function(event){
            // We need to make sure not to capture event on text fields
            if ( $(event.target).hasClass('form-control') ) {
                return;
            }
            if ( event.ctrlKey && (event.keyCode == 37) ) {
                first_page();
            }
            else if ( event.keyCode == 37 ) {
                prev_page();
            }
            else if ( event.ctrlKey && (event.keyCode == 39) ) {
                last_page();
            }
            else if ( event.keyCode == 39 ) {
                next_page();
            }
            else if ( event.keyCode == 107 ) {
                zoom_in();
            }
            else if ( event.keyCode == 109 ) {
                zoom_out();
            }
        });

        $(window).resize(function(){
            apply_zoom();
        });

        $( "#toggle_log" ).click(function() {
            log = !log;
            $( "#log_panel_body" ).toggle();
            // toggle icon
            $("span", this).toggleClass("glyphicon-chevron-down glyphicon-chevron-left");
        });

        $( "#mei_download" ).click(function() {
            outputFilename = outputFilename.replace(/\.[^\.]+$/, '.mei');
            saveAs(new Blob([vrvToolkit.getMEI(-1, true)], {type: "text/xml;charset=utf-8"}), outputFilename);
        });

        // Set the popover for the btn
        $( ".popover-btn" ).popover( );

        // Adjust the size of the svg_output and the zoom according to the div (screen) size
        width = $('#svg_panel').width();

        zoom = Math.min( Math.floor( 100 * width / 2100 ), zoom );

        // Init the swipe
        enable_swipe( true );

        // Load the default file or the file passed in the URL
        var file = verovioDiv.getAttribute('data-url');
        if (!file) {
            file = getParameterByName("file");
        }
        var musicxml = getParameterByName("musicxml");
        var local = getParameterByName("local");

        if (musicxml == "true") {
            format = 'musicxml';
            $("#mei_download").show();
        }

        if (local == "true") {
            data = localStorage.getItem("musicxml_file");
            outputFilename = localStorage.getItem("musicxml_filename");
            load_data( data );
        }
        else {
            if (!file || (file.length == 0)) {
                file = "examples/downloads/Chopin_Etude_op.10_no.9.mei";
            }
            else {
                target = window.location.hash;
            }
            $("#verovio").show();
            $.ajax({
                url: file
                , dataType: "text"
                , success: function(data) {
                    outputFilename = file.replace(/^.*[\\\/]/, '');
                    load_data( data );
                }
            });
        }
        $(".row-offcanvas").on('transitionend webkitTransitionEnd oTransitionEnd mozTransitionend MSTransitionEnd', function() {
            if (pageWidth != calc_page_width()) {
                apply_zoom();
            }
        });

        $("#player").midiPlayer({
            color: "#c00",
            onUpdate: midiUpdate,
            onStop: midiStop,
            width: 250
        });

        $("#pdfFormat").val(pdfFormat);
        $("#pdfOrientation").val(pdfOrientation);

        $('#pdfOK').click(function () {
            $('#pdfDialog').modal('hide');
            var pdfFormat = $("#pdfFormat").val();
            var pdfOrientation = $("#pdfOrientation").val();
            $.cookie('pdfFormat', pdfFormat, { expires: 30 });
            $.cookie('pdfOrientation', pdfOrientation, { expires: 30 });
            generate_pdf();
        });

        for (opt in disabledOptions) {
            $("#option-form :input[name='" + disabledOptions[opt] + "']").prop("disabled", true);
        }

        $("#option-form :input").change(function() {
            // Reset all options to default
            vrvToolkit.setOptions(vrvToolkit.getOptions(true));
            // console.log("Applying options");
            customOptions = non_default_options(JSON.parse($('#option-form').toJSON()));
            apply_zoom();
        });

        $("#optionDialog").on("show.bs.modal", function () {
            savedOptions = non_default_options(vrvToolkit.getOptions(false));
            var currentOptions = vrvToolkit.getOptions(false)
            var defaultOptions = vrvToolkit.getOptions(true);
            for(var key in defaultOptions) {

                if (disabledOptions.includes(key)) {
                    continue;
                }

                if (!Array.isArray(defaultOptions[key]) && (defaultOptions[key] != currentOptions[key])) {
                    $("label[for='" + key +"']").css("color", "#B00");
                }
                else {
                    $("label[for='" + key +"']").css("color", "");
                }
            }

            $("#option-form").fromJSON(JSON.stringify(currentOptions));
        });

        $("#optionDialog").on("hidden.bs.modal", function () {
            // This means the dialog was dismissed
            console.log(savedOptions);
            if (savedOptions !== undefined) {
                customOptions = savedOptions;
                savedOptions = undefined;
                //console.debug("Restoring options");
            }
            apply_zoom();
        });

        $('#optionOK').click(function () {
            savedOptions = undefined;
            $('#optionDialog').modal('hide');
        });

        $('#optionDefault').click(function () {
            savedOptions = undefined;
            customOptions = undefined;
            // Reset to default and clear local storage
            vrvToolkit.setOptions(vrvToolkit.getOptions(true));
            localStorage.clear('customOptions');
            //console.debug("Resetting options");
            $('#optionDialog').modal('hide');
        });
    });
//]]>
</script>

</div>

<script type="text/javascript">
    //<![CDATA[
    $(document).ready(function() {
        $('[data-toggle=offcanvas]').click(function() {
            $('.row-offcanvas').toggleClass('active');
        });
    });
    //]]>
</script>

<noscript>
    <p>
        <?= $this->escapeHtml($translate('This browser does not support javascript.')) ?>
        <?= sprintf($translate('You may %sdownload it%s to view it offline.'), '<a href="' . $media->originalUrl() . '">', '</a>') ?>
        <img src="<?= $media->thumbnailUrl('large') ?>" height="600px"/>
    </p>
</noscript>
