<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\MediaRepresentation $media
 * @var array $options
 */

$translate = $this->plugin('translate');
$assetUrl = $this->plugin('assetUrl');

$baseUrl = $this->serverUrl() . $assetUrl('vendor/verovio/js/', 'Verovio', false, false);

$this->headLink()
    ->appendStylesheet($assetUrl('css/verovio.css', 'Verovio'))
;
$this->headScript()
    ->appendFile($assetUrl('js/verovio.js', 'Verovio'), 'module')
;
?>

<div id="verovio" class="verovio" data-base-url="<?= $baseUrl ?>" data-url="<?= $media->originalUrl() ?>" <?= $options['attributes'] ?>><?= $translate('The viewer is loading…') ?></div>
<noscript>
    <p>
        <?= $this->escapeHtml($translate('This browser does not support javascript.')) ?>
        <?= sprintf($translate('You may %sdownload it%s to view it offline.'), '<a href="' . $media->originalUrl() . '">', '</a>') ?>
        <img src="<?= $media->thumbnailUrl('large') ?>" height="600px"/>
    </p>
</noscript>
